##### 1. 데이터 로딩 및 확인

In [2]:
import pandas as pd

In [3]:
card = './data/bccard_201906.csv'
card_df = pd.read_csv(card)
# 데이터 확인 앞부분
card_df.head()

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536

In [4]:
# 데이터 확인 : 뒷 부분
card_df.tail()

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [5]:
# 총 데이터 수
print(f"총 데이터 수 : {len(card_df)}")

총 데이터 수 : 100001

##### 2. 서울시 거주 / 비거주 고객 비교 분석

In [6]:
# 고객 수
custCount = len(card_df[card_df.CSTMR_MEGA_CTY_NM.isin(['서울특별시'])].value_counts())
nonSeoul = len(card_df[~card_df.CSTMR_MEGA_CTY_NM.isin(['서울특별시'])])
print(f'서울특별시 고객 수 : {custCount:,}')
print(f'서울 비거주 고객 수 : {nonSeoul:,}')

서울특별시 고객 수 : 54,150
서울 비거주 고객 수 : 45,851

In [7]:
# 카드 이용건수
cardCount = card_df.loc[card_df['CSTMR_MEGA_CTY_NM'] == '서울특별시', 'CNT'].sum()
print(f'총 서울특별시 고객 카드 이용 건수 : {cardCount}')

총 서울특별시 고객 카드 이용 건수 : 5542462

In [8]:
# 총 소비액
totalAMT = card_df.loc[card_df['CSTMR_MEGA_CTY_NM'] == '서울특별시', 'AMT'].sum()
print(f'총 서울특별시 고객 총 소비액 : {totalAMT:,} 원')

총 서울특별시 고객 총 소비액 : 119,663,142,676 원

### 편의점 소비액, 서울시 내 편의점 소비액

In [15]:
# 서울시 내 편의점 소비액
seoul_conv_df = card_df[(card_df['MEGA_CTY_NM'] == '서울특별시') & (card_df['TP_BUZ_NO'] == 4010)]
seoul_conv_amt = seoul_conv_df['AMT'].sum()

# 강남구 내 편의점 소비액
gangnam_conv_amt = seoul_conv_df.loc[seoul_conv_df['CTY_RGN_NM'] == '강남구', 'AMT'].sum()

print(f"서울시 전체 편의점 소비액: {seoul_conv_amt:,}원")
print(f'강남구 내 편의점 소비액 : {gangnam_conv_amt:,}원')

서울시 전체 편의점 소비액: 7,299,184,098원
강남구 내 편의점 소비액 : 707,275,140원

In [17]:
# 서울시 편의점 데이터(seoul_conv_df)를 기준으로 분류
# 서울 거주자
seoul_amt = seoul_conv_df.loc[seoul_conv_df['CSTMR_MEGA_CTY_NM'] == '서울특별시', 'AMT'].sum()

# 비거주자 (서울이 아닌 경우)
non_seoul_amt = seoul_conv_df.loc[seoul_conv_df['CSTMR_MEGA_CTY_NM'] != '서울특별시', 'AMT'].sum()

print(f"서울 편의점 이용 - 서울 거주자 소비액: {seoul_amt:,}원")
print(f"서울 편의점 이용 - 비거주자 소비액: {non_seoul_amt:,}원")

서울 편의점 이용 - 서울 거주자 소비액: 6,107,016,378원
서울 편의점 이용 - 비거주자 소비액: 1,192,167,720원